---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks: 
  - name: install packages
    yum: 
      name: "{{ item }}"
      state: installed
    with_items:
      - 'nmap'
      - 'htop'
      - 'gcc'
      - 'wget'
      - 'telnet'
      - 'gzip'
