---
- name: This playbook install packages
  hosts: webservers
  become: true
  tasks: 
  - name: install packages
    yum: 
      name: httpd
      state: installed
    notify: start apache

  handlers: 
  - name: start apache
    service:
      name: httpd
      state: started      
