---
- name: This playbook install httpd
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start apache

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start apache2

  - name: copy index.html
    copy: 
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
      
  handlers:
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: restart apache
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
